version = 1
SPDX-PackageName = "Gardener chaos-engineering"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/chaos-engineering"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "chaosgarden/vsphere/pchelper.py"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2021 VMware, Inc. All Rights Reserved."
SPDX-License-Identifier = "Apache-2.0"
