#!/usr/bin/env bash

# prepare script
set -e
repo_dir="$(readlink -f "$(dirname "$0")/..")"
dist_dir="$(readlink -f "${repo_dir}/dist")"
cd $repo_dir

# install buildtime dependencies
pip3 install --upgrade pip wheel setuptools twine

# build into dist dir
python3 "${repo_dir}/setup.py" sdist bdist_wheel

# retrieve PyPI credentials
model_element_cmd="gardener-ci config model_element --cfg-type pypi --cfg-name gardener"
username="$(${model_element_cmd} --key credentials.username)"
passwd="$(${model_element_cmd} --key credentials.passwd)"

# upload to PyPI
set -x
twine upload --user "${username}" --password "${passwd}" "${dist_dir}"/*
